theme = "tokyonight_storm"

[editor]
cursorline=true
auto-completion=true
true-color=true
bufferline="multiple"
idle-timeout=0
line-number="relative"

[editor.lsp]
enable=true
display-messages=true
auto-signature-help=true
display-inlay-hints=true
display-signature-help-docs=true
snippets=true
goto-reference-include-declaration=true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
